module.exports = [
  { "timezone": "Afghanistan", "code": "AF", "format": "Asia/Kabul", "currency": "AFN" },
  { "timezone": "Bahrain", "code": "BH", "format": "Asia/Bahrain", "currency": "BHD" },
  { "timezone": "Bangladesh", "code": "BD", "format": "Asia/Dhaka", "currency": "BDT" },
  { "timezone": "Brunei", "code": "BN", "format": "Asia/Brunei", "currency": "BND" },
  { "timezone": "Myanmar", "code": "MM", "format": "Asia/Yangon", "currency": "MMK" },
  { "timezone": "Cambodia", "code": "KH", "format": "Asia/Phnom_Penh", "currency": "KHR" },
  { "timezone": "Georgia", "code": "GE", "format": "Asia/Tbilisi", "currency": "GEL" },
  { "timezone": "Hong Kong", "code": "HK", "format": "Asia/Hong_Kong", "currency": "HKD" },
  { "timezone": "India", "code": "IN", "format": "Asia/Kolkata", "currency": "INR" },
  { "timezone": "Indonesia", "code": "ID", "format": "Asia/Jakarta", "currency": "IDR" },
  { "timezone": "Iran", "code": "IR", "format": "Asia/Tehran", "currency": "IRR" },
  { "timezone": "Israel", "code": "IL", "format": "Asia/Jerusalem", "currency": "ILS" },
  { "timezone": "Japan", "code": "JP", "format": "Asia/Tokyo", "currency": "JPY" },
  { "timezone": "South Korea", "code": "KR", "format": "Asia/Seoul", "currency": "KRW" },
  { "timezone": "North Korea", "code": "KP", "format": "Asia/Pyongyang", "currency": "KPW" },
  { "timezone": "Kuwait", "code": "KW", "format": "Asia/Kuwait", "currency": "KWD" },
  { "timezone": "Kyrgyzstan", "code": "KG", "format": "Asia/Bishkek", "currency": "KGS" },
  { "timezone": "Laos", "code": "LA", "format": "Asia/Vientiane", "currency": "LAK" },
  { "timezone": "Lebanon", "code": "LB", "format": "Asia/Beirut", "currency": "LBP" },
  { "timezone": "Macau", "code": "MO", "format": "Asia/Macau", "currency": "MOP" },
  { "timezone": "Malaysia", "code": "MY", "format": "Asia/Kuala_Lumpur", "currency": "MYR" },
  { "timezone": "Maldives", "code": "MV", "format": "Indian/Maldives", "currency": "MVR" },
  { "timezone": "Mongolia", "code": "MN", "format": "Asia/Ulaanbaatar", "currency": "MNT" },
  { "timezone": "Nepal", "code": "NP", "format": "Asia/Kathmandu", "currency": "NPR" },
  { "timezone": "Oman", "code": "OM", "format": "Asia/Muscat", "currency": "OMR" },
  { "timezone": "Pakistan", "code": "PK", "format": "Asia/Karachi", "currency": "PKR" },
  { "timezone": "Philippines", "code": "PH", "format": "Asia/Manila", "currency": "PHP" },
  { "timezone": "Qatar", "code": "QA", "format": "Asia/Qatar", "currency": "QAR" },
  { "timezone": "Saudi Arabia", "code": "SA", "format": "Asia/Riyadh", "currency": "SAR" },
  { "timezone": "Singapore", "code": "SG", "format": "Asia/Singapore", "currency": "SGD" },
  { "timezone": "Sri Lanka", "code": "LK", "format": "Asia/Colombo", "currency": "LKR" },
  { "timezone": "Taiwan", "code": "TW", "format": "Asia/Taipei", "currency": "TWD" },
  { "timezone": "Thailand", "code": "TH", "format": "Asia/Bangkok", "currency": "THB" },
  { "timezone": "Turkmenistan", "code": "TM", "format": "Asia/Ashgabat", "currency": "TMT" },
  { "timezone": "United Arab Emirates", "code": "AE", "format": "Asia/Dubai", "currency": "AED" },
  { "timezone": "Uzbekistan", "code": "UZ", "format": "Asia/Tashkent", "currency": "UZS" },
  { "timezone": "Vietnam", "code": "VN", "format": "Asia/Ho_Chi_Minh", "currency": "VND" },
  { "timezone": "Armenia", "code": "AM", "format": "Asia/Yerevan", "currency": "AMD" },
  { "timezone": "Azerbaijan", "code": "AZ", "format": "Asia/Baku", "currency": "AZN" },
  { "timezone": "Bahrain", "code": "BH", "format": "Asia/Bahrain", "currency": "BHD" },
  { "timezone": "Bhutan", "code": "BT", "format": "Asia/Thimphu", "currency": "BTN" },
  { "timezone": "Cyprus", "code": "CY", "format": "Asia/Nicosia", "currency": "EUR" },
  { "timezone": "Iraq", "code": "IQ", "format": "Asia/Baghdad", "currency": "IQD" },
  { "timezone": "Jordan", "code": "JO", "format": "Asia/Amman", "currency": "JOD" },
  { "timezone": "Kazakhstan", "code": "KZ", "format": "Asia/Almaty", "currency": "KZT" },
  { "timezone": "Palestine", "code": "PS", "format": "Asia/Gaza", "currency": "ILS" },
  { "timezone": "Syria", "code": "SY", "format": "Asia/Damascus", "currency": "SYP" },
  { "timezone": "Tajikistan", "code": "TJ", "format": "Asia/Dushanbe", "currency": "TJS" },
  { "timezone": "China", "code": "CN", "format": "Asia/Shanghai", "currency": "CNY" }
]
  